# Generated by Django 4.2.6 on 2023-10-29 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0004_alter_productos_cantidad_alter_productos_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="cantidad",
        ),
        migrations.AddField(
            model_name="productos",
            name="fechaSalida",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productos",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos"),
        ),
    ]
