# Generated by Django 4.2.6 on 2023-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0007_alter_productos_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="cantidad",
            field=models.IntegerField(),
        ),
    ]
