# Generated by Django 4.2.6 on 2023-10-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('ubicacion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('fechaLlegada', models.DateField(auto_now_add=True)),
                ('fechaSalida', models.DateField(auto_now_add=True)),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
